# Generated by Django 3.2 on 2021-07-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='level',
            field=models.CharField(choices=[('0', 'beginner'), ('1', 'junior'), ('2', 'mid'), ('3', 'senior')], default='0', max_length=1, verbose_name='Level'),
        ),
    ]
